package wise_samples.mtom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlMimeType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-b02- Generated source version: 2.0
 */
@WebService( name = "MTOM", targetNamespace = "http://wise_samples/MTOM" )
@SOAPBinding( parameterStyle = SOAPBinding.ParameterStyle.BARE )
public interface MTOM {

    /**
     * @param toWhom
     * @return returns byte[]
     */
    @WebMethod
    @WebResult( name = "result", targetNamespace = "http://wise_samples/MTOM", partName = "result" )
    @XmlMimeType( "text/plain" )
    public byte[] sayHello( @WebParam( name = "toWhom", targetNamespace = "http://wise_samples/MTOM", partName = "toWhom" ) String toWhom );

    /**
     * 
     * @param toWhomFoo
     * @return
     *     returns wise_samples.mtom.Foo
     */
    @WebMethod
    @WebResult(name = "resultFoo", targetNamespace = "http://wise_samples/MTOM", partName = "resultFoo")
    public Foo sayHelloFoo(
        @WebParam(name = "toWhomFoo", targetNamespace = "http://wise_samples/MTOM", partName = "toWhomFoo")
        String toWhomFoo);

}
