
package wise_samples.mtom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MTOM", targetNamespace = "http://wise_samples/MTOM")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MTOM {


    /**
     * 
     * @param toWhom
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://wise_samples/MTOM", partName = "result")
    public byte[] sayHello(
        @WebParam(name = "toWhom", targetNamespace = "http://wise_samples/MTOM", partName = "toWhom")
        String toWhom);

}
